### PR TITLE
fix: :bug: Increase max text length for controller text setting

### LINKED ISSUE #679: 🐛[BUG] - Controller text cuts off too early
### Describe the bug
When printing to the controller, the text cuts off earlier than it should.  

### To Reproduce
In a new project, run this code twice, switching which `master.set_test()` is ran.  
```cpp
void opcontrol() {
  pros::Controller master(pros::E_CONTROLLER_MASTER);

  while (true) {
    // master.set_text(2, 0, "0.0          0.0");  // both of these print to controller, but the second one isn't all the way to the right 
    master.set_text(2, 0, "0.0             0.0");  // with an additional 3 spaces, only the first 0.0 will print to controller
    
    pros::delay(50);
  }
}
```

### Expected Behavior
The text cutoff should be at the edge of the screen instead of somewhere in the middle.  

### Screenshots
The cutoff being early can be seen in the image below.  
image

### Desktop (please complete the following information):
 - Windows 10
 - Kernel 4.1.0
 - lvgl 8.3.8

### PR DESCRIPTION
**Pull request by ion098**
#### Summary:
Changes max length of controller text to 31 characters.

#### Motivation:
VEXCode allows users to set controller text with a maximum length of 31 characters, but PROS caps controller text at 15 characters.

##### References (optional):
Close #679

#### Test Plan:
- [x] Check it compiles
- [x] Check that controller text setting works with strings up to 31 characters long
- [x] Check that this doesn't break controller text clearing

### CODE REVIEW

**Review by AndrewLuGit — DISMISSED** [review]
LGTM

**Comment by liucougar** [comment]
this would be nice to have

File: src/devices/controller.c [hunk 1]
```diff
@@ -19,6 +19,7 @@
 #include "vdml/vdml.h"
 
 #define CONTROLLER_MAX_COLS 15
+#define CONTROLLER_MAX_CHARS 31
```
Comment (WillXuCodes) [inline src/devices/controller.c]: A couple of nits: 
- Might as well get rid of CONTROLLER_MAX_COLS
- Parenthesize and unsign the define

Other than that this looks good, thanks for the contribution :) 

```suggestion
#define CONTROLLER_MAX_CHARS ( 31U )
```

**Review by WillXuCodes — CHANGES_REQUESTED** [review]
Slight change requested

File: src/devices/controller.c (hunk 1 above)
Comment (ion098) [reply src/devices/controller.c]: Addressed in https://github.com/purduesigbots/pros/pull/683/commits/f907d62932d81042b081eac8641ee435cb3e5e18. (`CONTROLLER_MAX_COLS` still needs to be there since the controller only supports 20 columns, but can print 31 characters, due to the font being proportional).

File: src/devices/controller.c [hunk 2]
```diff
@@ -18,7 +18,8 @@
 #include "v5_api.h"
 #include "vdml/vdml.h"
 
-#define CONTROLLER_MAX_COLS 15
+#define CONTROLLER_MAX_COLS ( 20U )
```
Comment (AndrewLuGit) [inline src/devices/controller.c:21]: Why was this changed from 15 to 20?

Comment (ion098) [reply src/devices/controller.c:21]: Because VEXCode supports 20 columns:
image

**Review by AndrewLuGit — APPROVED** [review]
