### PR TITLE
🐛 Prevent LLEMU Clearing Segfault

### LINKED ISSUE #338: 🐛 pros::lcd::clear segfaults
#### Expected Behavior:

calling `pros::lcd::clear` should blank the lines on the screen

#### Actual Behavior:

image

#### Steps to reproduce:

call `pros::lcd::clear`

#### System information:
this has probably been present since LLEMU was implemented. not sure why this is the first user report i've seen about it

#### Additional Information

https://github.com/purduesigbots/pros/blob/c2dafd2d9d007f8d22e09b7de3a9d38ad88575c4/src/display/llemu.c#L175-L180

i'm not sure why i wrote this comment because it's just not true. replacing the contents of this function with 
```c
for (size_t i = 0; i < 8; i++)
    _lcd_clear_line(lcd_dummy, i);
```
should be sufficient to fix the issue

#### Screenshots/Output Dumps/Stack Traces
```
DATA ABORT EXCEPTION

CURRENT TASK: User Autonomous (PROS)
REGISTERS AT ABORT
 r0: 0x039d64f4  r1: 0x03ae2840  r2: 0x007f00ff  r3: 0x00005cc1  r4: 0x038000dc  r5: 0x039d64f4  r6: 0x03910b4f  r7: 0x00005cc1
 r8: 0x08080808  r9: 0x09090909 r10: 0x10101010 r11: 0x11111111 r12: 0x039d6505  sp: 0x03ae27b0  lr: 0x0382ff7c  pc: 0x0381a610

BEGIN STACK TRACE
    0x381a610
    0x382ff7c
END OF TRACE
HEAP USED: 5176 bytes
STACK REMAINING AT ABORT: 4293901365 bytes
```

```
0x0381a610: lv_obj_get_style at lv_obj.c:1526
0x0382ff7c: lv_label_refr_text at lv_label.c:794
```

per user who reported the above, commenting out their call to `pros::lcd::clear` causes the program to function normally, as does running a custom looping clear function instead of `pros::lcd::clear`

### PR DESCRIPTION
**Pull request by WillXuCodes**
#### Summary:
This prevents a segfault that occurs when the LCD on LLEMU is cleared.

##### References (optional):
closes #338 

#### Test Plan:
- [x] Attempt to clear the LCD and see if a segfault occurs w/ the new code.

### CODE REVIEW

File: src/display/llemu.c [hunk 1]
```diff
@@ -172,13 +176,6 @@ bool _lcd_set_text(lv_obj_t* lcd_dummy, int16_t line, const char* text) {
...
 
-void _lcd_clear(lv_obj_t* lcd_dummy) {
-	lcd_s_t* lcd = lv_obj_get_ext_attr(lcd_dummy);
-	// delete children of screen (this is fine because when we print, we just
-	// overwrite the pointer anyway)
-	lv_obj_clean(lcd->screen);
-}
-
 bool _lcd_clear_line(lv_obj_t* lcd_dummy, int16_t line) {
 	if (line < 0 || line > 7) {
```
Comment (Jerrylum) [inline src/display/llemu.c:180]: change to `if (line < 0 || line > (LLEMU_LINES - 1)) {`

**Review by Jerrylum — CHANGES_REQUESTED** [review]
suggestion

File: src/display/llemu.c [hunk 2]
```diff
@@ -23,6 +23,10 @@
 #include "kapi.h"
 #include "pros/llemu.h"
 
+#define LCD_W 		480
```
Comment (HotelCalifornia) [inline src/display/llemu.c:26]: come on there's no penalty for verbosity here

File: src/display/llemu.c [hunk 3]
```diff
@@ -189,6 +186,11 @@ bool _lcd_clear_line(lv_obj_t* lcd_dummy, int16_t line) {
 	return true;
 }
 
+void _lcd_clear(lv_obj_t* lcd_dummy) {
+	for (size_t i = 0; i < LLEMU_LINES; i++)
+    	_lcd_clear_line(lcd_dummy, i);
```
Comment (HotelCalifornia) [inline src/display/llemu.c:191]: fix indentation in this function and add braces for the loop

Comment (AyushShukla3) [reply src/display/llemu.c:191]: The indentation looks good to me. Not sure why it looks different on github.

**Comment by AyushShukla3** [comment]
Tested the following code:
```c
void opcontrol() {
	pros::lcd::set_text(3, "Clear me");
	pros::lcd::clear(); 
}
```
All text on screen was cleared successfully
image

File: src/display/llemu.c (hunk 3 above)
Comment (Jerrylum) [reply src/display/llemu.c:191]: I think we should use tabs here

**Comment by WillXuCodes** [comment]
> Tested the following code:
> 
> ```c
> void opcontrol() {
> 	pros::lcd::set_text(3, "Clear me");
> 	pros::lcd::clear(); 
> }
> ```
> 
> All text on screen was cleared successfully image

Will merge after my interview in a couple hours, but I do want to note that the tabs vs spaces thing has not been fixed yet because github doesn't detect the diff. The workaround to this would be to delete the tabs entirely in one commit, then adding them back properly in the next.

**Comment by Jerrylum** [comment]
Please also change line 154 `if (line < 0 || line > 7) {`

**Comment by AyushShukla3** [comment]
> Will merge after my interview in a couple hours, but I do want to note that the tabs vs spaces thing has not been fixed yet because github doesn't detect the diff. The workaround to this would be to delete the tabs entirely in one commit, then adding them back properly in the next.

On my last commit it shows a difference

**Review by AyushShukla3 — APPROVED** [review]
Looks good
