### PR TITLE
✨ Add Zeroing and Position Setting Functions for the IMU

### LINKED ISSUE #252: pros::IMU : Add relative value functions such as set_rotation(), set_heading(), reset_rotation(), reset_heading() etc.
#### Expected Behavior:
set IMU sensor's rotation, yaw and heading to zero value; currently IMU retains the value from the prev reading. 

#### Actual Behavior:
I would like to reset IMU sensor's rotation to zero prior to every turn and don't see method to reset_rotation() like robotmesh api. Are there any methods available to reset heading, rotation etc. in the IMU without actually calibrating the IMU prior to each turn or movement...

#### Steps to reproduce:
none

#### System information:
Platform: V5
PROS Kernel Version:  3.2.1

#### Additional Information
none

### PR DESCRIPTION
**Pull request by WillXuCodes**
#### Summary:
Added zeroing and current value setting for readings for the IMU.

#### Motivation:
Requested via issue, might as well add this feature as it would be beneficial for writing autons.

#### References:
closes #252 

#### Test Plan:

- [x] Test Reset Functions (C API)
- [x] Test Reset Functions (C++ API)
- [x] Test Value Set Functions (C API)
- [x] Test Value Set Functions (C ++API)

### CODE REVIEW

File: include/pros/imu.hpp [hunk 1]
```diff
@@ -196,7 +201,232 @@ class Imu {
...
+	 * ENXIO - The given value is not within the range of V5 ports (1-21).
+	 * ENODEV - The port cannot be configured as an Inertial Sensor
+	 * EAGAIN - The sensor is still calibrating
+	 *
+	 * \param  port
+	 * 				 The V5 Inertial Sensor port number from 1-21
+	 * \return 1 if the operation was successful or PROS_ERR if the operation
+	 * failed, setting errno.
+	 */
+	virtual std::int32_t reset_rotation();
```
Comment (nathan-moore) [inline include/pros/imu.hpp:217]: Consider making a reset all one. I image that would be a common use.

**Review by nathan-moore — COMMENTED** [review]
A couple of other thoughts :

This is moving away from the long held tradition of having the cpp object being a view over a singleton kernel side. I don't disagree with this, but you'll have to make sure the docs are clear on this.

A complicated topic here is thread safety.  Pretty much everything is in pros, and these really should follow. While practically they aren't not thread safe, they're in the realm of technically not and should be wrapped in the mutex.  It'll be a bit of work, since imu_get_* takes (what I think is) a non-recursive mutex.

File: include/pros/imu.hpp [hunk 2]
```diff
@@ -24,9 +24,14 @@
...
 	const std::uint8_t _port;
-
 	public:
-	Imu(const std::uint8_t port) : _port(port){};
+	Imu(const std::uint8_t port) : _port(port){
+		this->_heading_offset = 0; 
+		this->_rotation_offset = 0; 
+		this->_pitch_offset = 0; 
+		this->_yaw_offset = 0;
+		this->_roll_offset = 0;
```
[the remark this answers is not in the document]
Comment (WillXuCodes) [reply include/pros/imu.hpp:33]: sorry that's my old Java tendencies popping back up :/

**Comment by WillXuCodes** [comment]
> This is moving away from the long held tradition of having the cpp object being a view over a singleton kernel side. I don't disagree with this, but you'll have to make sure the docs are clear on this.

I'm very aware of this, and I made the decision to make this feature cpp only as making the zeroing feature available in the C api would create breaking changes (since I'd have to create some sort of typedef for a new IMU object. (Unless you have other ideas for this).

**Comment by WillXuCodes** [comment]
> A complicated topic here is thread safety. Pretty much everything is in pros, and these really should follow. While practically they aren't not thread safe, they're in the realm of technically not and should be wrapped in the mutex. It'll be a bit of work, since imu_get_* takes (what I think is) a non-recursive mutex.

Going to get on making these thread safe and fixing other requested changes.

**Comment by HotelCalifornia** [comment]
> > This is moving away from the long held tradition of having the cpp object being a view over a singleton kernel side. I don't disagree with this, but you'll have to make sure the docs are clear on this.
> 
> I'm very aware of this, and I made the decision to make this feature cpp only as making the zeroing feature available in the C api would create breaking changes (since I'd have to create some sort of typedef for a new IMU object. (Unless you have other ideas for this).

Yes, when this feature was initially discussed we acknowledged and expected that it would be provided in the C++ API only. As will says, it would be nontrivial to add to the C API and doing so would frankly offer little benefit for the majority of our users

**Comment by baylessj** [comment]
I don't mean to throw the direction of this PR totally off course, but it should be feasible to implement this in the C API first. There is a 128 byte padding adding to the device struct for each of the 21 smart devices that can be used for holding internal state. The motors use this for saving their PID constants and the ADI uses this for storing a variety of state about the connected sensors. The state that is being added to the C++ class for this functionality could be stored instead in the registry padding.

This solution is not nearly as easy or clean as storing state in the C++ class but would have the benefits of sticking to the singleton convention that Nathan mentioned and maintaining feature parity with the C API. It sounds as though the vast majority of competitors have switched to using C++ though, so I'm not sure how important maintaining the C-first API design is anymore. Wanted to clarify that it is possible though.

File: include/pros/imu.h [hunk 3]
```diff
@@ -276,6 +276,198 @@ imu_status_e_t imu_get_status(uint8_t port);
...
+ * EAGAIN - The sensor is still calibrating
+ *
+ * \param  port
+ * 				 The V5 Inertial Sensor port number from 1-21
+ * \return 1 if the operation was successful or PROS_ERR if the operation
+ * failed, setting errno.
+ */
+int32_t imu_set_yaw(uint8_t port, double target);
+
+//Offset Getter Functions (Internal Usage, Not Thread Safe)
```
Comment (nathan-moore) [inline include/pros/imu.h:457]: You're adding these in the pr. If they aren't used remove them or put in an internal header.

File: version [hunk 4]
```diff
@@ -1 +1 @@
-3.3.1
+3.3.2-dirty.24.6a3540a
```
Comment (baylessj) [inline version:1]: you'll want to revert this change to prevent an accidental version bump. We might want to brainstorm some solutions on keeping this from accidentally updating; I got caught by this a number of times too

Comment (WillXuCodes) [reply version:1]: yep, will do when this PR Is done. I have an issue right now where the yaw, roll, and pitch functions aren't working properly so I'm going to work that out in a bit.

**Comment by WillXuCodes** [comment]
Other Noteable Changes in this PR:
-Updated license years in file headers.
-Fixed distance and optical sensor headers with the proper file name.

File: include/pros/imu.h [hunk 5]
```diff
@@ -74,7 +74,7 @@ typedef struct __attribute__((__packed__)) euler_s {
  * \return 1 if the operation was successful or PROS_ERR if the operation
  * failed, setting errno.
  */
-int32_t imu_reset(uint8_t port);
+int32_t imu_calibrate(uint8_t port);
```
Comment (nathan-moore) [inline include/pros/imu.h:77]:
```suggestion
int32_t imu_recalibrate(uint8_t port);
```
would be my suggestion since a calibration is already started for you. I'm waffling on this though. I know more then a couple people call this and I don't want to break their code, but the name is kind of bad...

File: include/pros/imu.hpp [hunk 6]
```diff
@@ -206,8 +206,173 @@ class Imu {
 	 *
 	 * \param  port
 	 * 				 The V5 Inertial Sensor port number from 1-21
-	 * \return The raw accelerometer values. If the operation failed, all the
-	 * structure's members are filled with PROS_ERR_F and errno is set.
+	 * \return 1 if the operation was successful or PROS_ERR if the operation
+	 * failed, setting errno.
+	 */
+	virtual std::int32_t reset_rotation() const;
```
Comment (nathan-moore) [inline include/pros/imu.hpp:212]: I know it's existing practice, but I was never a fan of these "constant" functions that mutated things.

File: include/pros/imu.hpp [hunk 7]
```diff
@@ -235,4 +400,4 @@ class Imu {
 };
 }  // namespace pros
 
-#endif
+#endif
```
Comment (nathan-moore) [inline include/pros/imu.hpp:403]: nit: revert removing the new line

File: src/devices/vdml_imu.c [hunk 8]
```diff
@@ -22,7 +23,11 @@
 		return_port(port - 1, err_return);                                         \
 	}
 
-int32_t imu_reset(uint8_t port) {
+typedef struct imu_reset_data { 
+	double heading_offset, rotation_offset, pitch_offset, yaw_offset, roll_offset;
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:27]: I believe that these should all be declared on a new line in our style.

File: src/devices/vdml_imu.c [hunk 9]
```diff
@@ -156,3 +184,135 @@ imu_status_e_t imu_get_status(uint8_t port) {
...
+	}
+	v5_smart_device_s_t* device = registry_get_device(port - 1);
+	ERROR_IMU_STILL_CALIBRATING(port, device, PROS_ERR);
+	imu_set_yaw_offset(port - 1, target - imu_get_euler_bl(port).yaw);
+	return_port(port - 1, 1);
+}
+
+//Internal functions for getting IMU offsets (Not thread safe)
+double imu_get_heading_offset(uint8_t port){
+    return ((imu_data_s_t*)registry_get_device(port)->pad)->heading_offset;
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:275]: My advice would be to factor getting the imu_data_s_t into a helper, and add an assert that's the struct is smaller then however much memory you get.

File: include/pros/imu.hpp [hunk 10]
```diff
@@ -206,8 +206,173 @@ class Imu {
...
+	 * EAGAIN - The sensor is still calibrating
+	 *
+	 * \param  port
+	 * 				 The V5 Inertial Sensor port number from 1-21
+	 * \return 1 if the operation was successful or PROS_ERR if the operation
+	 * failed, setting errno.
+	 */
+	virtual std::int32_t set_roll(double target) const;
+	/**
+	 *  Get the current offset of the IMU's rotation reading from its true value
```
Comment (nathan-moore) [inline include/pros/imu.hpp:364]: Did you change these docs? This doesn't make sense for get_accel.

File: include/pros/imu.hpp (hunk 6 above)
Comment (nathan-moore) [reply include/pros/imu.hpp:212]: Probably a thing for later though.

File: src/devices/vdml_imu.c [hunk 11]
```diff
@@ -22,7 +23,11 @@
 		return_port(port - 1, err_return);                                         \
 	}
 
-int32_t imu_reset(uint8_t port) {
+typedef struct imu_reset_data {
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:26]: Have you double checked that this fits in the registry? You may also want to pack the struct.

File: include/vdml/imubl.h [hunk 12]
```diff
@@ -0,0 +1,210 @@
+/**
+ * \file pros/imubl.h
+ *
+ * IMU Backend Layer header for non-threadsafe functions for reset
+ * functions that interact with the registry.
```
Comment (nathan-moore) [inline include/vdml/imubl.h:5]: I'm curious what others think of this. I personally don't think it's worth it to bother exposing these. We don't really need to expose 3 ways of setting the offset... The getters I don't see a use for.

File: src/devices/vdml_imu.c (hunk 11 above)
Comment (WillXuCodes) [reply src/devices/vdml_imu.c]: Struct packed, I'm pretty sure it fits in the registry (6 doubles at 8 bytes each being 48 bytes total, fitting into 128 bytes on the pad in the registry).

File: include/vdml/imubl.h (hunk 12 above)
Comment (WillXuCodes) [reply include/vdml/imubl.h:5]: in the process of reworking this to not have this at all.

File: include/pros/imu.h (hunk 5 above)
Comment (WillXuCodes) [reply include/pros/imu.h:77]: going to change this back to reset so it doesn't break user code, and changing the imu_reset function that resets all values to reset_all (or something better if you have another suggestion).

File: include/pros/imu.hpp [hunk 13]
```diff
@@ -196,7 +196,172 @@ class Imu {
...
+	 * EAGAIN - The sensor is still calibrating
+	 *
+	 * \param  port
+	 * 				 The V5 Inertial Sensor port number from 1-21
+	 * \return 1 if the operation was successful or PROS_ERR if the operation
+	 * failed, setting errno.
+	 */
+	virtual std::int32_t tare_pitch() const;
+	/**
+	 * Resets the current reading of the Inertial Sensor's pitch to zero
```
Comment (nathan-moore) [inline include/pros/imu.hpp:244]:
```suggestion
	 * Resets the current reading of the Inertial Sensor's yaw to zero
```

File: src/devices/vdml_imu.c [hunk 14]
```diff
@@ -97,15 +105,42 @@ euler_s_t imu_get_euler(uint8_t port) {
...
 
 double imu_get_pitch(uint8_t port) {
-	return imu_get_euler(port).pitch;
+	double rtn = PROS_ERR_F;
+	if (!claim_port_try(port - 1, E_DEVICE_IMU)) {
+		return rtn;
+	}
+	euler_s_t euler_values;
+	v5_smart_device_s_t* device;
+	device = registry_get_device(port - 1);
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:114]: Why split the definition and where you set it?

File: src/devices/vdml_imu.c [hunk 15]
```diff
@@ -156,3 +191,106 @@ imu_status_e_t imu_get_status(uint8_t port) {
...
+	v5_smart_device_s_t* device = registry_get_device(port - 1);
+	euler_s_t euler_values;
+	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
+	imu_data_s_t* data = (imu_data_s_t*)device->pad;
+	data->rotation_offset = -vexDeviceImuHeadingGet(device->device_info);
+	data->heading_offset = -vexDeviceImuDegreesGet(device->device_info);
+	data->pitch_offset = -euler_values.pitch;
+	data->roll_offset = -euler_values.roll;
+	data->yaw_offset = -euler_values.yaw;
+	return_port(port - 1, 1);
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:209]:
```suggestion
	return_port(port - 1, PROS_SUCCESS);
```

File: src/devices/vdml_imu.c [hunk 16]
```diff
@@ -97,15 +105,42 @@ euler_s_t imu_get_euler(uint8_t port) {
...
 
 double imu_get_roll(uint8_t port) {
-	return imu_get_euler(port).roll;
+	double rtn = PROS_ERR_F;
+	if (!claim_port_try(port - 1, E_DEVICE_IMU)) {
+		return rtn;
+	}
+	euler_s_t euler_values;
+	v5_smart_device_s_t* device;
+	device = registry_get_device(port - 1);
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:127]: Same here

File: src/devices/vdml_imu.c [hunk 17]
```diff
@@ -97,15 +105,42 @@ euler_s_t imu_get_euler(uint8_t port) {
...
 
 double imu_get_yaw(uint8_t port) {
-	return imu_get_euler(port).yaw;
+	double rtn = PROS_ERR_F;
+	if (!claim_port_try(port - 1, E_DEVICE_IMU)) {
+		return rtn;
+	}
+	euler_s_t euler_values;
+	v5_smart_device_s_t* device;
+	device = registry_get_device(port - 1);
```
Comment (nathan-moore) [inline src/devices/vdml_imu.c:140]: And here

**Review by nathan-moore — DISMISSED** [review]

File: src/devices/vdml_imu.c (hunk 15 above)
Comment (nathan-moore) [reply src/devices/vdml_imu.c:209]: For all of these that return 1

File: src/devices/vdml_imu.c (hunk 14 above)
Comment (WillXuCodes) [reply src/devices/vdml_imu.c:114]: Honestly, I did it because I saw that somebody else did it in another portion of the code so I thought it was the precedent for the project :/. Was wondering the same thing as you.

File: src/devices/vdml_imu.c (hunk 16 above)
Comment (WillXuCodes) [reply src/devices/vdml_imu.c:127]: Got it, will fix for previous code as well. Should I also take a look around and fix the other sensors in a seperate PR for this issue?

File: src/devices/vdml_imu.c (hunk 15 above)
Comment (WillXuCodes) [reply src/devices/vdml_imu.c:201]: Note for future reference: PROS_SUCCESS does not exist but we should add it in PROS 4 for readability's sake.

**Comment by nathan-moore** [comment]
How will this interact with imu_get_quaternion(uint8_t port) and imu_get_euler? Currently the ignore the values.

**Comment by WillXuCodes** [comment]
> How will this interact with imu_get_quaternion and imu_get_euler? Currently they ignore the offsets.

Honestly, I didn't think many people used them other than people who write libraries. I guess we could implement the offsets with those too if needed.

**Comment by nathan-moore** [comment]
> Honestly, I didn't think many people used them other than people who write libraries (who may prefer the raw values instead). I guess we could implement the offsets with those too if needed.

I don't think it's right to introduce a concept such as "raw values". From an outside perspective, there's the angle the imu reports, and that's it. The offset that we keep is an implementation detail. Beside, get_header and such were originally implemented to be a simpler get_euler.

File: include/api.h [hunk 18]
```diff
@@ -41,8 +41,8 @@
 
 #define PROS_VERSION_MAJOR 3
 #define PROS_VERSION_MINOR 3
-#define PROS_VERSION_PATCH 1
-#define PROS_VERSION_STRING "3.3.1"
+#define PROS_VERSION_PATCH 2
+#define PROS_VERSION_STRING "3.3.2-dirty.49.63955a5"
```
Comment (HotelCalifornia) [inline include/api.h:45]: fix this

File: version [hunk 19]
```diff
@@ -1 +1 @@
-3.3.1
+3.3.2-dirty.49.63955a5
```
Comment (HotelCalifornia) [inline version:1]: fix

File: src/main.cpp [hunk 20]
```diff
@@ -7,13 +7,7 @@
  * "I was pressed!" and nothing.
```
Comment (HotelCalifornia) [inline src/main.cpp:7]: this file should not be modified

**Review by HotelCalifornia — CHANGES_REQUESTED** [review]

**Comment by HotelCalifornia** [comment]
there's also compilation errors you're going to need to resolve here

File: include/pros/imu.hpp [hunk 21]
```diff
@@ -89,7 +89,7 @@ class Imu {
 	 * Get the Inertial Sensor's heading relative to the initial direction of its
 	 * x-axis
 	 *
-	 * This value is bounded by (-360,360). Clockwise rotations are represented with
+	 * This value is bounded by (0,360). Clockwise rotations are represented with
```
Comment (HotelCalifornia) [inline include/pros/imu.hpp:92]: same as above re: intervals

File: include/pros/imu.h [hunk 22]
```diff
@@ -57,6 +57,10 @@ typedef struct __attribute__((__packed__)) euler_s {
 } euler_s_t;
 
 #define IMU_MINIMUM_DATA_RATE 5
+#define IMU_EULER_LIMIT 180
+#define IMU_HEADING_MAX 360
+
+#define DEGTORAD (M_PI / 180)
```
Comment (HotelCalifornia) [inline include/pros/imu.h:63]: unless these are used in this header file somewhere, they should probably get moved to the source file. avoid adding internal values/utilities to the public interface wherever possible

Comment (HotelCalifornia) [reply include/pros/imu.h:63]: (and yes DEGTORAD may be useful for users but in the interests of separation of concern it should at the very least not be defined in this file, if it's to be given to our users at all)
(which i think it shouldn't be, especially because this is the kind of symbol commonly defined by users anyway and to define it here now might cause conflicts)

File: include/pros/imu.h [hunk 23]
```diff
@@ -465,7 +471,8 @@ int32_t imu_set_pitch(uint8_t port, double target);
 
 /**
  * Sets the current reading of the Inertial Sensor's roll to target value
- *
+ * Will default to +/- 180 if value target +/- 180.
```
Comment (HotelCalifornia) [inline include/pros/imu.h:474]: is this line supposed to be the same as the others?

File: src/devices/vdml_imu.c [hunk 24]
```diff
@@ -82,13 +82,24 @@ quaternion_s_t imu_get_quaternion(uint8_t port) {
...
+	double roll = euler.roll + data->roll_offset;
+	double yaw = euler.yaw + data->yaw_offset;
+	double pitch = euler.pitch + data->pitch_offset;
+
+	if(roll > IMU_EULER_LIMIT) roll -= 2 * IMU_EULER_LIMIT;
+	if(roll < -IMU_EULER_LIMIT) roll += 2 * IMU_EULER_LIMIT;
+	if(yaw > IMU_EULER_LIMIT) yaw -= 2 * IMU_EULER_LIMIT;
+	if(yaw < -IMU_EULER_LIMIT) yaw += 2 * IMU_EULER_LIMIT;
+	if(pitch > IMU_EULER_LIMIT) pitch -= 2 * IMU_EULER_LIMIT;
+	if(pitch < -IMU_EULER_LIMIT) pitch += 2 * IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:95]: these should all be `if (...)`

File: src/devices/vdml_imu.c [hunk 25]
```diff
@@ -113,6 +124,12 @@ euler_s_t imu_get_euler(uint8_t port) {
 	rtn.pitch += data->pitch_offset;
 	rtn.yaw += data->yaw_offset;
 	rtn.roll += data->roll_offset;
+	if(rtn.roll > IMU_EULER_LIMIT) rtn.roll -= 2 * IMU_EULER_LIMIT;
+	if(rtn.roll < -IMU_EULER_LIMIT) rtn.roll += 2 * IMU_EULER_LIMIT;
+	if(rtn.yaw > IMU_EULER_LIMIT) rtn.yaw -= 2 * IMU_EULER_LIMIT;
+	if(rtn.yaw < -IMU_EULER_LIMIT) rtn.yaw += 2 * IMU_EULER_LIMIT;
+	if(rtn.pitch > IMU_EULER_LIMIT) rtn.pitch -= 2 * IMU_EULER_LIMIT;
+	if(rtn.pitch < -IMU_EULER_LIMIT) rtn.pitch += 2 * IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:132]: these should all be `if (...)`

File: src/devices/vdml_imu.c [hunk 26]
```diff
@@ -125,6 +142,8 @@ double imu_get_pitch(uint8_t port) {
 	v5_smart_device_s_t* device = registry_get_device(port - 1);
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	rtn = euler_values.pitch + ((imu_data_s_t*)registry_get_device(port - 1)->pad)->pitch_offset;
+	if(rtn > IMU_EULER_LIMIT) rtn -= 2 * IMU_EULER_LIMIT;
+	if(rtn < -IMU_EULER_LIMIT) rtn += 2 * IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:146]: `if (...)`

File: src/devices/vdml_imu.c [hunk 27]
```diff
@@ -137,6 +156,8 @@ double imu_get_roll(uint8_t port) {
 	v5_smart_device_s_t* device = registry_get_device(port - 1);
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	rtn = euler_values.roll + ((imu_data_s_t*)registry_get_device(port - 1)->pad)->roll_offset;
+	if(rtn > IMU_EULER_LIMIT) rtn -= 2 * IMU_EULER_LIMIT;
+	if(rtn < -IMU_EULER_LIMIT) rtn += 2 * IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:160]: `if (...)`

File: src/devices/vdml_imu.c [hunk 28]
```diff
@@ -149,6 +170,8 @@ double imu_get_yaw(uint8_t port) {
 	v5_smart_device_s_t* device = registry_get_device(port - 1);
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	rtn = euler_values.yaw + ((imu_data_s_t*)registry_get_device(port - 1)->pad)->yaw_offset;
+	if(rtn > IMU_EULER_LIMIT) rtn -= 2 * IMU_EULER_LIMIT;
+	if(rtn < -IMU_EULER_LIMIT) rtn += 2 * IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:174]: `if (...)`

File: src/devices/vdml_imu.c [hunk 29]
```diff
@@ -262,7 +285,9 @@ int32_t imu_set_heading(uint8_t port, double target){
 	euler_s_t euler_values;
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	imu_data_s_t* data = (imu_data_s_t*)device->pad;
-	data->heading_offset = (target - vexDeviceImuDegreesGet(device->device_info)) % 360;
+	if(target > IMU_HEADING_MAX) target = IMU_HEADING_MAX;
+	if(target < 0) target = 0;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:289]: you know the drill

File: src/devices/vdml_imu.c [hunk 30]
```diff
@@ -275,7 +300,9 @@ int32_t imu_set_pitch(uint8_t port, double target){
 	euler_s_t euler_values;
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	imu_data_s_t* data = (imu_data_s_t*)device->pad;
-	data->pitch_offset = (target - euler_values.pitch) % 90;
+	if(target > IMU_EULER_LIMIT) target = IMU_EULER_LIMIT;
+	if(target < -IMU_EULER_LIMIT) target = -IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:304]: here too

File: src/devices/vdml_imu.c [hunk 31]
```diff
@@ -288,7 +315,9 @@ int32_t imu_set_roll(uint8_t port, double target){
 	euler_s_t euler_values;
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	imu_data_s_t* data = (imu_data_s_t*)device->pad;
-	data->roll_offset = (target - euler_values.roll) % 90;
+	if(target > IMU_EULER_LIMIT) target = IMU_EULER_LIMIT;
+	if(target < -IMU_EULER_LIMIT) target = -IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:319]: and here

File: src/devices/vdml_imu.c [hunk 32]
```diff
@@ -301,7 +330,9 @@ int32_t imu_set_yaw(uint8_t port, double target){
 	euler_s_t euler_values;
 	vexDeviceImuAttitudeGet(device->device_info, (V5_DeviceImuAttitude*)&euler_values);
 	imu_data_s_t* data = (imu_data_s_t*)device->pad;
-	data->yaw_offset = (target - euler_values.yaw) % 90;
+	data->yaw_offset = target - euler_values.yaw;
+	if(target > IMU_EULER_LIMIT) target = IMU_EULER_LIMIT;
+	if(target < -IMU_EULER_LIMIT) target = -IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:335]: here

File: src/devices/vdml_imu.c [hunk 33]
```diff
@@ -313,8 +344,14 @@ int32_t imu_set_euler(uint8_t port, euler_s_t target){
...
 	imu_data_s_t* data = (imu_data_s_t*)device->pad;
-	data->pitch_offset = (target.pitch - euler_values.pitch) % 90;
-	data->roll_offset = (target.roll - euler_values.roll) % 90;
-	data->yaw_offset = (target.yaw - euler_values.yaw) % 90;
+	if(target.pitch > IMU_EULER_LIMIT) target.pitch = IMU_EULER_LIMIT;
+	if(target.pitch < -IMU_EULER_LIMIT) target.pitch = -IMU_EULER_LIMIT;
+	if(target.yaw > IMU_EULER_LIMIT) target.yaw = IMU_EULER_LIMIT;
+	if(target.yaw < -IMU_EULER_LIMIT) target.yaw = -IMU_EULER_LIMIT;
+	if(target.roll > IMU_EULER_LIMIT) target.roll = IMU_EULER_LIMIT;
+	if(target.roll < -IMU_EULER_LIMIT) target.roll = -IMU_EULER_LIMIT;
```
Comment (HotelCalifornia) [inline src/devices/vdml_imu.c:352]: all of these

**Review by HotelCalifornia — COMMENTED** [review]
some minor style things but other than those this looks good to me

File: include/pros/imu.h (hunk 23 above)
Comment (WillXuCodes) [reply include/pros/imu.h:470]: yes, I'm trying to say that if the target value is above or below +180 and -180 respectively, it will default to +180 or -180.

Comment (HotelCalifornia) [reply include/pros/imu.h:470]: right, but the wording here is inexplicably different from the others

Comment (WillXuCodes) [reply include/pros/imu.h:470]: All three euler values have their bounds at -180 and 180, and each setter function has the same feature.

**Review by HotelCalifornia — APPROVED** [review]
lgtm
