### PR TITLE
👽 Add missing filesystem syscalls

### LINKED ISSUE #273: Mock or implement symlink
On really new versions of libstdc++, it now exposes the symlink syscall. This prevents hot/cold linking when using that version. This syscall should either be implemented or mocked to do nothing.

#### Screenshots/Output Dumps/Stack Traces

Here's the compile error for it:

Creating cold package with libc,libm,libpros,okapilib [ERRORS]
/usr/local/lib/pros-toolchain/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /usr/local/lib/pros-toolchain/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/lib/thumb/v7-a+simd/softfp/libstdc++.a(cow-fs_ops.o): in function `std::filesystem::create_directory_symlink(std::filesystem::path const&, std::filesystem::path const&, std::error_code&)':
cow-fs_ops.cc:(.text._ZNSt10filesystem24create_directory_symlinkERKNS_4pathES2_RSt10error_code+0x8): undefined reference to `symlink'

### PR DESCRIPTION
**Pull request by kunwarsahni01**
#### Summary:
Adds missing File System stubs: symlink, readlink, truncate, fchmod, fchmodat.

#### Motivation:
Dependencies on these syscalls were added with the gcc-arm-none-eabi-10-2020-q4-major update (in c++20-compliant std::filesystem functions)

##### References (optional):
Closes #273

### CODE REVIEW

File: src/system/dev/file_system_stubs.c [hunk 1]
```diff
@@ -56,3 +56,28 @@ int _stat(const char* file, struct stat* st) {
...
 }
+
+int symlink(const char* file, const char* linkpath) {
+	errno = ENOSYS;
+	return -1;
+}
+
+ssize_t readlink(const char* pathname, char* buf, size_t bufsiz) {
+	errno = ENOSYS;
+	return NULL;
```
Comment (nathan-moore) [inline src/system/dev/file_system_stubs.c:67]:
```suggestion
	return -1;

```

**Review by nathan-moore — COMMENTED** [review]
How did you decide which syscalls to implement?

**Comment by kunwarsahni01** [comment]
> How did you decide which syscalls to implement?
These were the syscalls missing when installing. 
Screen Shot 2021-01-09 at 12 23 25 AM

File: src/system/dev/file_system_stubs.c [hunk 2]
```diff
@@ -56,3 +56,29 @@ int _stat(const char* file, struct stat* st) {
...
+	return -1;
+
+}
+
+int truncate(const char* path, off_t length) {
+	errno = ENOSYS;
+	return -1;
+}
+
+int fchmod(int fd, mode_t mode) {
```
Comment (nathan-moore) [inline src/system/dev/file_system_stubs.c:76]: nit: put fchmod and fchmodat by chmod

**Review by nathan-moore — APPROVED** [review]

**Review by HotelCalifornia — APPROVED** [review]

**Comment by HotelCalifornia** [comment]
motivation: work out of the box with the gcc-arm-none-eabi-10-2020-q4-major update
